build:
  nodes:
    analysis:
      project_setup:
        override:
        - 'true'
      tests:
        override:
        - php-scrutinizer-run
        -
          command: phpcs-run
          use_website_config: true
    tests-and-coverage:
      tests:
        override:
        -   command: ./vendor/bin/phpunit
            coverage:
              file: build/logs/clover.xml
              format: clover
filter:
  excluded_paths:
  - 'tests/*'
checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        bitwise: false
        concatenation: true